---
title: "PORT: preliminary analyses"
author: "Thomas McGregor"
date: "`r Sys.Date()`"
output: html_document
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = "../reports"
    )
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r load packages, include=FALSE}
# Clear workspace
rm(list = ls())

# Load packages
library(gt) # creating tables
library(here) # file referencing
library(naniar) # visualise missing data
library(ppcor) # partial correlations
library(tidyverse) # data manipulation
library(webshot) # required for saving gt tables
```

```{r read in dataset, include=FALSE}
port_data <- read_rds(here("data", "processed", "merged", "07_imputed-processed-data.Rds"))

port_data_exclusions_applied <- port_data %>% 
  filter(port_exclusion != TRUE)
```

# Demographics
```{r}
port_data_exclusions_applied %>%
  dplyr::select(age = demographics_age_at_screening,
                sex = demographics_biological_sex,
                n_sessions = ieso_treatment_completed_total,
                gad7_baseline = gad7_baseline_total,
                gad7_change = gad7_treatment_change_observed) %>%
  group_by(sex) %>%
  summarise(
    n = n(),
    mean_age = mean(age, na.rm = TRUE),
    mean_gad7 = mean(gad7_baseline, na.rm = TRUE),
    mean_gad7_change = mean(gad7_change, na.rm = TRUE),
    median_sessions = median(n_sessions, na.rm = TRUE)
  ) %>%
  pivot_longer(cols = -sex, names_to = "variable", values_to = "value") %>% 
  pivot_wider(names_from = "sex", values_from = "value") %>% 
  mutate(variable = recode(variable,
         n = "n",
         mean_age = "Mean age",
         mean_gad7 = "Mean GAD-7 study baseline",
         mean_gad7_change = "Mean GAD-7 change",
         median_sessions = "Median number of sessions")) %>% 
  gt() %>%  
  cols_label(
    variable = "",
    female = md("**Female**"),
    male = md("**Male**")
  ) %>% 
  tab_header(title = "PORT Study Demographics") %>% 
  fmt_number(columns = where(is.numeric),
             decimals = 2)
```


# Cleaning

## Subsetting
```{r}
port_data_subsetted <- port_data %>% 
  filter(port_exclusion == FALSE) %>% 
  dplyr::select(
    gad7_treatment_total_final,
    gad7_treatment_total_final_observed,
    exp_acquisition_cs_minus_mean,
    exp_extinction_cs_plus_mean,
    gad7_treatment_total_1,
    ieso_treatment_completed_total,
    fss_baseline_total,
    fss_followup_total)

port_data_subsetted_complete_cases <- na.omit(port_data_subsetted)
```

## Visualise missing data
```{r}
port_data_subsetted %>%  
vis_miss()
```

## Skew & kurtosis


# Analyses

## Acquisition CS-

```{r}
acquisition_cs_minus_model <- port_data_subsetted %>% 
  lm(
    gad7_treatment_total_final_observed ~ exp_acquisition_cs_minus_mean + gad7_treatment_total_1 + ieso_treatment_completed_total, 
    data = .
  )

pcor.test(
  port_data_subsetted_complete_cases$gad7_treatment_total_final_observed,
  port_data_subsetted_complete_cases$exp_acquisition_cs_minus_mean,
  port_data_subsetted_complete_cases$gad7_treatment_total_1,
  method="pearson"
)

summary(acquisition_cs_minus_model)

port_data_subsetted %>% 
  ggplot(aes(x = exp_acquisition_cs_minus_mean, y = gad7_treatment_total_final_observed)) +
  geom_point() + 
  geom_smooth(method=lm)
```

## Extinction CS+

```{r}
extinction_cs_plus_model <- port_data_subsetted %>% 
  lm(gad7_treatment_total_final_observed ~ exp_extinction_cs_plus_mean + gad7_treatment_total_1 + ieso_treatment_completed_total, data = .)

pcor.test(port_data_subsetted_complete_cases$gad7_treatment_total_final_observed,
          port_data_subsetted_complete_cases$exp_extinction_cs_plus_mean,
          port_data_subsetted_complete_cases$gad7_treatment_total_1,
          method="pearson")

summary(extinction_cs_plus_model)

port_data_subsetted %>% 
  ggplot(aes(x = exp_extinction_cs_plus_mean, y = gad7_treatment_total_final_observed)) +
  geom_point() + 
  geom_smooth(method=lm)
```


## FSS

```{r}
fss_model <- port_data_subsetted %>% 
  lm(fss_followup_total ~ exp_extinction_cs_plus_mean + fss_baseline_total + ieso_treatment_completed_total, data = .)

pcor.test(port_data_subsetted_complete_cases$fss_followup_total,
          port_data_subsetted_complete_cases$exp_extinction_cs_plus_mean,
          port_data_subsetted_complete_cases$fss_baseline_total,
          method="pearson")

summary(fss_model)

port_data_subsetted %>% 
  ggplot(aes(x = exp_extinction_cs_plus_mean, y = fss_followup_total)) +
  geom_point() + 
  geom_smooth(method=lm)
```

# Visualisation

```{r}
port_data_exclusions_applied <- port_data %>% 
  filter(port_exclusion != TRUE)
```



```{r}
data_viz_transformed <- port_data_exclusions_applied %>%
  select(
    participant_id,
    gad7_assessment_total,
    matches("gad7_treatment_total_\\d*$"),
    phq9_assessment_total,
    matches("phq9_treatment_total_\\d*$")
  ) %>%
  pivot_longer(
    cols = c(
      gad7_assessment_total,
      matches("gad7_treatment_total_\\d*$"),
      phq9_assessment_total,
      matches("phq9_treatment_total_\\d*$")
    ),
    names_to = "session",
    values_to = "score"
  ) %>%
  mutate(
    session = case_when(
      session == "gad7_assessment_total" ~ "gad7_treatment_total_0",
      session == "phq9_assessment_total" ~ "phq9_treatment_total_0",
      TRUE ~ session
    )
  ) %>%
  separate(
    session,
    into = c("measure", "type", "x", "session"),
    sep = c("_", "_", "_"),
    convert = TRUE
  ) %>%
  select(-c(type, x)) %>%
  group_by(measure, session) %>%
  summarise(across(
    .cols = score,
    .fns = list(
      mean = ~ mean(.x, na.rm = TRUE),
      sd = ~ sd(.x, na.rm = TRUE),
      sample_size = ~ sum(!is.na(.x))
    ),
    .names = "{.fn}",
    .groups = "keep"
  )) %>%
  ungroup() %>%
  mutate(
    se = sd / sqrt(sample_size),
    se_lower = mean - se,
    se_upper = mean + se
  )

data_viz_transformed %>%
  filter(session < 12) %>%
  ggplot(., aes(x = session, y = mean, color = measure)) +
  geom_point() +
  geom_line() +
  geom_ribbon(
    aes(ymin = se_lower, ymax = se_upper, fill = measure),
    alpha = 0.1,
    linetype = 0
  ) +
  theme_minimal() +
  geom_text(aes(label = sample_size), nudge_y = .3, size = 3) +
  scale_x_continuous(breaks = seq(0, 11, by = 1)) +
  facet_wrap(~measure)
```

## Elephant

```{r Elephant wrangling, include=FALSE}
# Create a list of expectancy rating trial variables
elephant_long <- port_data_exclusions_applied %>% 
  select(matches("^exp_.*\\d$")) %>%
  mutate(n = nrow(.)) %>% 
  pivot_longer(cols = -n, names_to = "variable", values_to = "rating") %>% 
  mutate(variable = str_remove(variable, "exp_")) %>%
  separate(variable, into = c("phase", "cs", "stimulus", "trial"), sep = "_") %>% 
  select(-cs) %>% 
  mutate(trial = as.numeric(trial)) %>% 
  group_by(phase, stimulus, trial) %>% 
  summarise(mean = mean(rating, na.rm = T), std_dev = sd(rating, na.rm = T), n = mean(n), .groups = "keep") %>% 
  mutate(sem = std_dev / sqrt(n),
         ci_low = mean - 2*(sem),
         ci_high = mean + 2*(sem)) %>% 
  ungroup() %>% 
  mutate(Phase = str_to_sentence(phase),
         Phase = factor(Phase, levels = c("Acquisition", "Extinction")),
         Stimulus = factor(stimulus, levels = c("plus", "minus")),
         Stimulus = fct_recode(Stimulus, "CS+" = "plus", "CS-" = "minus")) %>% 
  select(Phase, Stimulus, Trial = trial, everything()) %>% 
  select(-c(phase, stimulus)) %>% 
  arrange(Phase, Stimulus, Trial)

# Function for breaks
breaks_fun <- function(x) {
  if (max(x) > 12) {
    seq(0, 18, 1)
  } else {
    seq(0, 12, 1)
  }
}
```

```{r}
elephant_plot_exclusions_applied <- elephant_long %>% 
  ggplot(aes(x = Trial, y = mean, color = Stimulus)) +
  geom_point() +
  geom_line() +
  geom_ribbon(aes(ymin = ci_low, ymax = ci_high, fill = Stimulus),
              linetype = 0,
              alpha = 0.3,
              size = 0.8
  ) +
  scale_fill_manual(values = c("#DF3B57", "#5762D5")) +
  scale_colour_manual(values = c("#DF3B57", "#5762D5")) +
  facet_grid(~ Phase, 
               scales = "free_x",
               space = "free_x"
    ) +
    # adjust the labels
    labs(y="Mean expectancy rating", 
         x = "Trials"
    ) +
    theme(strip.background = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          legend.position = 'bottom',
          text = element_text(size = 10),
          strip.text.x = element_text(size = 10)
    ) +
    scale_x_continuous(breaks = breaks_fun) +
    scale_y_continuous(breaks = seq(0, 10, by = 1), limits = c(1, 9))

# Save
ggsave(
  file = paste0(here("reports", "figures"), "/elephant-plot_exclusions-applied.png"), 
  plot = elephant_plot_exclusions_applied, 
  width = 16, 
  height = 8, 
  units = "cm"
  )
```
