---
title: "PORT: descriptives"
author: "Thomas McGregor"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    df_print: paged
    highlight: monochrome
    number_sections: no
    theme: flatly
    toc: true
    toc_float: 
      collapsed: true
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = "../reports"
    )
  })
---

# Setup
```{r load packages, include=FALSE}
# Clear workspace
rm(list = ls())

# Load packages
library(broom) # tidying output
library(confintr) # effect size for chisq
library(gt) # creating tables
library(gtsummary) # creating tables
library(here) # file referencing
library(infer) # tidy stats
library(naniar) # missing data
library(ppcor) # partial correlations
library(summarytools) # data exploration
library(tidyverse) # data manipulation
library(webshot) # required for saving gt tables

# Source function script
source(file = here("r", "functions.R"))
```

```{r read in dataset, include=FALSE}
port_data <-
  read_rds(here(
    "data",
    "processed",
    "merged",
    "07_imputed-processed-data.Rds"
  ))
```

# Cleaning

## Subsets

```{r create subsets}
# Exclusions applied: all variables, filtered participants
port_data_exclusions_applied <- 
  port_data %>% 
  filter(port_exclusion == FALSE)

# Completed baseline measures (for comparisons with analytical sample)
port_completed_baseline <- 
  port_data %>% 
  filter(flare_completed_app == TRUE)

# Subsetted: selected variables, filtered participants
port_data_subsetted <- 
  port_data %>% 
  filter(port_exclusion == FALSE) %>% 
  select(
    ieso_treatment_completed_total,
    demographics_age_at_screening_years,
    demographics_biological_sex,
    gad7_treatment_total_1,
    gad7_treatment_total_final,
    gad7_treatment_total_final_observed,
    gad7_followup_total,
    exp_acquisition_cs_minus_mean,
    exp_extinction_cs_plus_mean,
    fss_baseline_total,
    fss_followup_total)

# Subsetted, complete cases: selected variables, filtered participants, no 
# missing data
port_data_subsetted_complete_cases <- 
  na.omit(port_data_subsetted)
```

# Recruitment flow

## Figure 1 flow

```{r}
port_data %>%
  # Filter for participants with screening eligibility = 293
  filter(port_screening_eligibility == TRUE) %>%
  # Summarise numbers at different stages
  summarise(
    completed_flare_n = sum(flare_completed_app == TRUE,
                            na.rm = TRUE),
    not_referred_n = sum(
      flare_completed_app == TRUE &
        ieso_referral == FALSE &
        flare_exclusion_port == TRUE,
      na.rm = TRUE
    ),
    did_not_complete_referral_n = sum(
      flare_completed_app == TRUE &
        ieso_referral == FALSE &
        flare_exclusion_port == FALSE,
      na.rm = TRUE
    ),
    ieso_referral_n = sum(flare_completed_app == TRUE &
                            ieso_referral == TRUE,
                          na.rm = TRUE),
    flare_exclusion_n = sum(
      flare_completed_app == TRUE &
        ieso_referral == TRUE &
        flare_exclusion_port == TRUE,
      na.rm = TRUE
    ),
    ieso_exclusion_n = sum(
      flare_completed_app == TRUE &
        ieso_referral == TRUE &
        flare_exclusion_port == FALSE &
        ieso_exclusion_port == TRUE,
      na.rm = TRUE
    ),
    primary_analyses_n = sum(
        port_exclusion == FALSE,
      na.rm = TRUE
    ),
    completed_followup_n = sum(
        port_exclusion == FALSE &
      followup_complete == TRUE,
      na.rm = TRUE
    )
  )
```

## Results section counts

```{r}
port_data %>%
  filter(flare_completed_app == TRUE) %>%
  summarise(
    completed_flare_n = sum(flare_completed_app == TRUE,
                            na.rm = TRUE),
    not_flare_excluded_not_referred = sum(
      flare_completed_app == TRUE &
        flare_exclusion_port == FALSE &
        ieso_referral == FALSE,
      na.rm = TRUE
    ),
    flare_exclusion_not_referred_n = sum(
      flare_completed_app == TRUE &
        flare_exclusion_port == TRUE &
        ieso_referral == FALSE,
      na.rm = TRUE
    ),
    flare_exclusion_referred_n = sum(
      flare_completed_app == TRUE &
        flare_exclusion_port == TRUE &
        ieso_referral == TRUE,
      na.rm = TRUE
    ),
    ieso_referral_overall_n = sum(flare_completed_app == TRUE &
                                    ieso_referral == TRUE,
                                  na.rm = TRUE),
    post_referral_flare_exclusion_n = sum(
      flare_completed_app == TRUE &
        ieso_referral == TRUE &
        flare_exclusion_port == TRUE,
      na.rm = TRUE
    ),
    ieso_exclusion_n = sum(
      flare_completed_app == TRUE &
        ieso_referral == TRUE &
        flare_exclusion_port == FALSE &
        ieso_exclusion_port == TRUE,
      na.rm = TRUE
    ),
    ieso_2sessions_exclusion_n = sum(
      flare_completed_app == TRUE &
        ieso_referral == TRUE &
        flare_exclusion_port == FALSE &
        ieso_exclusion_port == TRUE &
        (
          ieso_treatment_completed_total < 2 |
            is.na(ieso_treatment_completed_total)
        ),
      na.rm = TRUE
    ),
    ieso_not_suitable_exclusion_n = sum(
      flare_completed_app == TRUE &
        ieso_referral == TRUE &
        flare_exclusion_port == FALSE &
        ieso_exclusion_port == TRUE &
        ieso_treatment_completed_total >= 2 &
        ieso_discharge_reason_primary == "not_suitable_for_service",
      na.rm = TRUE
    )
  ) %>% 
  pivot_longer(everything(), names_to = "var", values_to = "n")
```


# Demographics

## Exclusions vs analytical sample comparison

Compare:
-   Age
-   Sex
-   Baseline GAD-7

```{r}
# Table for comparing exclusions to analytical sample
# Chisq test calculated separately as providing seemingly incorrect results as 
# part of tbl_summary
port_completed_baseline %>%
  select(
    port_exclusion,
    demographics_age_at_screening_years,
    gad7_baseline_total
  ) %>%
  tbl_summary(
    by = port_exclusion,
    type = list(demographics_age_at_screening_years ~ "continuous2",
                gad7_baseline_total ~ "continuous2"),
    label = c(
      demographics_age_at_screening_years ~ "Age (years)",
      gad7_baseline_total ~ "GAD-7 baseline"
    ),
    statistic = all_continuous() ~ c("{mean} ({sd})"),
    missing = "ifany",
    digits = list(all_continuous() ~ c(1))
  ) %>%
  add_difference(all_continuous() ~ "cohens_d") %>% 
  add_p(all_continuous() ~ "t.test",
        pvalue_fun = ~ style_pvalue(.x, digits = 2)) %>%
  
  modify_header(
    statistic = "**statistic**",
    parameter = "**df**"
  )

sex_chisq_results <- chisq.test(table(port_completed_baseline$demographics_biological_sex, port_completed_baseline$port_exclusion))

sex_chisq_results

cramersv(sex_chisq_results)
```


## Analytical sample

```{r}
port_data_exclusions_applied %>% 
  group_by(demographics_ethnic_origin) %>% 
  count()
```


```{r demographics table, message=FALSE}
demographics_data <-
  port_data_exclusions_applied %>%
  
  mutate(
    # Capitalise categories for sex variable
    demographics_biological_sex =
      factor(str_to_title(demographics_biological_sex)),
      demographics_ethnic_origin = 
      droplevels(fct_infreq(str_to_title(demographics_ethnic_origin)))
  ) %>%
  
  # Select variables
  select(
    demographics_age_at_screening_years,
    demographics_biological_sex,
    demographics_ethnic_origin,
    ieso_treatment_completed_total,
    gad7_treatment_total_1,
    gad7_treatment_change_observed
  )

# Create gt summary table
demographics_table <-
  demographics_data %>%
  tbl_summary(
    label = list(
      demographics_age_at_screening_years ~ "Age (years)",
      demographics_biological_sex ~ "Sex assigned at birth",
      demographics_ethnic_origin ~ "Ethnicity",
      ieso_treatment_completed_total ~ "Treatment sessions completed",
      gad7_treatment_total_1 ~ "GAD-7 prior to first treatment session",
      gad7_treatment_change_observed ~ "GAD-7 treatment change"
    ),
    
    statistic = list(
      demographics_age_at_screening_years ~ "{mean} ({sd})",
      ieso_treatment_completed_total ~ "{mean} ({sd})",
      gad7_treatment_total_1 ~ "{mean} ({sd})",
      gad7_treatment_change_observed ~ "{mean} ({sd})"
    ),
    
    digits = list(
      demographics_age_at_screening_years ~ 1,
      demographics_biological_sex ~ 0,
      demographics_ethnic_origin ~ 0,
      ieso_treatment_completed_total ~ 1,
      gad7_treatment_total_1 ~ 1,
      gad7_treatment_change_observed ~ 1
    ),
    
    missing_text = "Missing"
    
  ) %>%
  modify_header(label = "**Variable**") %>%
  bold_labels() %>%
  as_gt() %>%
  gt::tab_options(table.font.names = "Arial",
                  table.font.size = 11)

# Print demographics display table
demographics_table

# Save table
suppressMessages(gtsave(
  demographics_table,
  filename = here("reports", "tables", "demographics_table.png"),
  expand = 10
))
```

# Diagnoses and treatment protocol

```{r diagnosis and treatment protocol table}


diagnosis_treatment_data <-
  port_data_exclusions_applied %>%
  
  # Capitalise categories and remove underscores
  transmute(
    across(
      .cols = c(ieso_diagnosis_name,
                ieso_protocol_token),
      .fns = ~ str_to_title(.) %>%
        str_replace_all("_", " ") %>%
        factor() %>%
        fct_infreq()
    )
  ) %>%
  # Collapse categories where counts are fewer than 5
  # Doing this after the above so that the category appears at the bottom
  mutate(across(
    .cols = c(ieso_diagnosis_name,
              ieso_protocol_token),
    .fns = ~ fct_lump_min(.x, min = 5, other_level = "Other - low count")
  )) %>%
  # Rename the 'Other' level of ieso_protocol_token
  mutate(
    ieso_diagnosis_name = fct_recode(
      ieso_diagnosis_name,
      `Panic disorder (episodic paroxysmal anxiety)` = 
        "Panic disorder episodic paroxysmal anxiety"
    ),
    ieso_protocol_token =
      fct_recode(
        ieso_protocol_token,
        `Other - not described` = "Other",
        `Low intensity GAD` = "S2 gad",
        `Fennell` = "Melaine"
      )
  )


# Create gt summary table
diagnosis_treatment_table <-
  diagnosis_treatment_data %>%
  tbl_summary(
    label = list(
      ieso_diagnosis_name ~ "Primary diagnosis",
      ieso_protocol_token ~ "Protocol"
    ),
    
    missing_text = "Missing"
    
  ) %>%
  modify_header(label = "**Variable**") %>%
  bold_labels() %>%
  as_gt() %>%
  gt::tab_options(table.font.names = "Arial",
                  table.font.size = 11)

# Print demographics display table
diagnosis_treatment_table

# Save table
suppressMessages(gtsave(
  diagnosis_treatment_table,
  filename = here("reports", "tables", "diagnosis_treatment_table.png"),
  expand = 10
))
```

# IAPT categories

```{r}
port_data_exclusions_applied %>% 
  select(iapt_reliable_improvement_observed, iapt_recovery_observed, iapt_rcsi_observed) %>% 
  na.omit %>% 
  ggplot(aes(x = iapt_reliable_improvement_observed, fill = fct_rev(as.character(iapt_recovery_observed)))) +
  geom_bar() +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank()) +
  scale_fill_manual(values = c("#811D1C", "#153860"))
```

## Fear conditioning
```{r}
port_data_exclusions_applied %>% 
  group_by(iapt_rcsi_observed) %>% 
  summarise(n = n(),
            mean_acq_plus = mean(exp_acquisition_cs_plus_mean, na.rm = TRUE),
            mean_acq_minus = mean(exp_acquisition_cs_minus_mean, na.rm = TRUE),
            mean_ext_plus = mean(exp_extinction_cs_plus_mean, na.rm = TRUE),
            mean_ext_minus = mean(exp_extinction_cs_minus_mean, na.rm = TRUE))
```

# Symptom trajectories

```{r}
data_viz_transformed <- port_data_exclusions_applied %>%
  select(
    participant_id,
    gad7_assessment_total,
    matches("gad7_treatment_total_\\d*$"),
    phq9_assessment_total,
    matches("phq9_treatment_total_\\d*$")
  ) %>%
  pivot_longer(
    cols = c(
      gad7_assessment_total,
      matches("gad7_treatment_total_\\d*$"),
      phq9_assessment_total,
      matches("phq9_treatment_total_\\d*$")
    ),
    names_to = "session",
    values_to = "score"
  ) %>%
  mutate(
    session = case_when(
      session == "gad7_assessment_total" ~ "gad7_treatment_total_0",
      session == "phq9_assessment_total" ~ "phq9_treatment_total_0",
      TRUE ~ session
    )
  ) %>%
  separate_wider_delim(
    session,
    names = c("measure", "type", "x", "session"),
    delim = "_"
  ) %>%
  select(-c(type, x)) %>%
  mutate(session = as.numeric(session)) %>% 
  group_by(measure, session) %>%
  summarise(across(
    .cols = score,
    .fns = list(
      mean = ~ mean(.x, na.rm = TRUE),
      sd = ~ sd(.x, na.rm = TRUE),
      sample_size = ~ sum(!is.na(.x))
    ),
    .names = "{.fn}"
  )) %>%
  ungroup() %>%
  mutate(
    se = sd / sqrt(sample_size),
    se_lower = mean - se,
    se_upper = mean + se
  )

data_viz_transformed %>%
  filter(session < 12,
         measure == "gad7") %>%
  ggplot(., aes(x = session, y = mean, color = measure)) +
  geom_point() +
  geom_line() +
  geom_ribbon(
    aes(ymin = se_lower, ymax = se_upper, fill = measure),
    alpha = 0.1,
    linetype = 0
  ) +
  theme_minimal() +
  geom_text(aes(label = sample_size), nudge_y = 1, size = 3) +
  scale_x_continuous(breaks = seq(0, 11, by = 1)) +
  scale_y_continuous(limits = c(0, 21), breaks = seq(0, 21, by = 3)) +
  labs(title = "Average GAD-7 score over the course of treatment",
       x = "Treatment session",
       y = "Average GAD-7 score",
       caption = "Number above each point indicates sample size") +
  scale_color_manual(values = "#153860") +
  scale_fill_manual(values = "#153860") +
  theme(legend.position = "none",
        panel.grid.minor = element_blank())

ggsave(here("reports", "figures", "symptom-trajectory.png"),
  bg = "white")
```

# Interpretation biases